---
- name: Установка и настройка  Prometheus
  hosts: monitoring_servers
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    prometheus_version: "3.7.3"

  tasks:
    - name: Создание пользователя для Prometheus
      user:
        name: prometheus
        system: yes
        shell: /sbin/nologin
        home: /var/lib/prometheus
        create_home: yes

    - name: Создание директорий Prometheus
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
      loop:
        - /etc/prometheus
        - /var/lib/prometheus
        - /var/lib/prometheus/data

    - name: Загрузка Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"

    - name: Распакова Prometheus
      unarchive:
        src:  "/tmp/prometheus.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Копирование бинарников Prometheus
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: prometheus
        group: prometheus
        mode: "0755"
      loop:
        - prometheus
        - promtool

    - name: Найстройка конфига Prometheus
      template:
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: 0644

    - name: Настройка systemd сервиса Prometheus
      copy:
        content: |
          [Unit]
          Descriprion=Prometheus Time Series Collection and Processing Server
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus/data \
            --web.console.templates=/etc/prometheus/consoles \
            --web.console.libraries=/etc/prometheus/console_libraries \
            --web.listen-address=:9090

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/prometheus.service
        mode: 0644

    - name: Перезагрузка systemd
      systemd:
        daemon_reload: yes

    - name: Запуск Prometheus
      systemd:
        name: prometheus
        enabled: yes
        state: started

  handlers:
    - name: restart prometheus
      systemd:
        name: prometheus
        state: restarted


           

